In [1]:
import pandas as pdty
import numpy as np

In [2]:
import cv2 #computervison

In [3]:
import time #timetofphoto
import datetime #dateoftheday

In [4]:
face_detect = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

In [5]:
source = cv2.VideoCapture(0)
input_images = []
targets = []
count = 0
for i in range(2):
    no_of_images = 0
    input("Enter to start")
    while 1:
        _,image = source.read(0)
        gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
        detected_faces = face_detect.detectMultiScale(gray, 1.2, 9)
        if len(detected_faces) > 1:
            continue
        for each_face in detected_faces:
            x, y, w, h = each_face
            cv2.rectangle(image,(x,y), (x+w, y+h),(0, 0, 255), 3)
            crop = gray[y:y+h, x:x+w]
            cropped_image = cv2.resize(crop,(100, 100))
            input_images.append(cropped_image)
            targets.append(count)

            no_of_images += 1
            cv2.putText(image, "image no : " + str(no_of_images), (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1,(100,100,100), 2)

            cv2.imshow('project', cropped_image)
            key = cv2.waitKey(1)
            cv2.imshow("face window", image)
        if no_of_images == 5000 :
               break

    count += 1

    cv2.destroyAllWindows()
source.release()

In [6]:
input_images

[array([[231, 230, 227, ..., 192, 186, 186],
        [226, 224, 224, ..., 188, 186, 183],
        [222, 221, 222, ..., 192, 191, 186],
        ...,
        [209, 208, 206, ..., 202, 210, 209],
        [208, 205, 202, ..., 207, 210, 208],
        [199, 190, 176, ..., 207, 206, 206]], dtype=uint8),
 array([[184, 182, 182, ..., 166, 159, 157],
        [179, 181, 180, ..., 165, 164, 160],
        [179, 178, 177, ..., 158, 159, 162],
        ...,
        [138, 139, 139, ..., 171, 173, 177],
        [137, 134, 135, ..., 170, 172, 178],
        [136, 131, 134, ..., 172, 171, 172]], dtype=uint8),
 array([[184, 183, 182, ..., 160, 161, 162],
        [183, 182, 182, ..., 162, 160, 161],
        [180, 179, 181, ..., 164, 160, 163],
        ...,
        [139, 139, 137, ..., 172, 175, 177],
        [141, 141, 139, ..., 174, 174, 175],
        [135, 131, 135, ..., 176, 176, 177]], dtype=uint8),
 array([[192, 189, 190, ..., 165, 167, 167],
        [191, 188, 188, ..., 163, 165, 165],
        [188, 18

In [7]:
len(input_images)

10000

In [8]:
len(targets)

10000

In [9]:
input_images_normalized = np.array(input_images)/255.0
input_images_normalized

array([[[0.90588235, 0.90196078, 0.89019608, ..., 0.75294118,
         0.72941176, 0.72941176],
        [0.88627451, 0.87843137, 0.87843137, ..., 0.7372549 ,
         0.72941176, 0.71764706],
        [0.87058824, 0.86666667, 0.87058824, ..., 0.75294118,
         0.74901961, 0.72941176],
        ...,
        [0.81960784, 0.81568627, 0.80784314, ..., 0.79215686,
         0.82352941, 0.81960784],
        [0.81568627, 0.80392157, 0.79215686, ..., 0.81176471,
         0.82352941, 0.81568627],
        [0.78039216, 0.74509804, 0.69019608, ..., 0.81176471,
         0.80784314, 0.80784314]],

       [[0.72156863, 0.71372549, 0.71372549, ..., 0.65098039,
         0.62352941, 0.61568627],
        [0.70196078, 0.70980392, 0.70588235, ..., 0.64705882,
         0.64313725, 0.62745098],
        [0.70196078, 0.69803922, 0.69411765, ..., 0.61960784,
         0.62352941, 0.63529412],
        ...,
        [0.54117647, 0.54509804, 0.54509804, ..., 0.67058824,
         0.67843137, 0.69411765],
        [0.5

In [10]:
input_images_normalized_reshaped = input_images_normalized.reshape(10000, 100, 100, 1)
input_images_normalized_reshaped

array([[[[0.90588235],
         [0.90196078],
         [0.89019608],
         ...,
         [0.75294118],
         [0.72941176],
         [0.72941176]],

        [[0.88627451],
         [0.87843137],
         [0.87843137],
         ...,
         [0.7372549 ],
         [0.72941176],
         [0.71764706]],

        [[0.87058824],
         [0.86666667],
         [0.87058824],
         ...,
         [0.75294118],
         [0.74901961],
         [0.72941176]],

        ...,

        [[0.81960784],
         [0.81568627],
         [0.80784314],
         ...,
         [0.79215686],
         [0.82352941],
         [0.81960784]],

        [[0.81568627],
         [0.80392157],
         [0.79215686],
         ...,
         [0.81176471],
         [0.82352941],
         [0.81568627]],

        [[0.78039216],
         [0.74509804],
         [0.69019608],
         ...,
         [0.81176471],
         [0.80784314],
         [0.80784314]]],


       [[[0.72156863],
         [0.71372549],
         [0.71

In [11]:
from keras.utils import to_categorical
targets = to_categorical(targets)
targets

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [12]:
targets[ : 100]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(input_images_normalized_reshaped, targets)

In [15]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((7500, 100, 100, 1), (2500, 100, 100, 1), (7500, 2), (2500, 2))

In [16]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Conv2D, MaxPooling2D, Dropout, Flatten
from tensorflow.keras.optimizers import SGD
from keras.callbacks import ModelCheckpoint

In [17]:
model = Sequential()
model.add(Conv2D(300, (3,3),input_shape=(100, 100, 1)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(100, (3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.3))
model.add(Flatten())

model.add(Dense(50, activation='relu'))
model.add(Dense(2, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

c:\Users\Nanditha\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
cp = ModelCheckpoint('best_one.keras', verbose=0, save_best_only=True)
model.fit(x_train, y_train, epochs = 3, callbacks=[cp], validation_split=0.2)

Epoch 1/3
188/188 ━━━━━━━━━━━━━━━━━━━━ 138s 722ms/step - accuracy: 0.6367 - loss: 0.6181 - val_accuracy: 0.8487 - val_loss: 0.3431
Epoch 2/3
188/188 ━━━━━━━━━━━━━━━━━━━━ 135s 718ms/step - accuracy: 0.8572 - loss: 0.3263 - val_accuracy: 0.8893 - val_loss: 0.2584
Epoch 3/3
188/188 ━━━━━━━━━━━━━━━━━━━━ 140s 743ms/step - accuracy: 0.8893 - loss: 0.2593 - val_accuracy: 0.9633 - val_loss: 0.1273


In [19]:
from tensorflow.keras.models import load_model
model = load_model('best_one.keras')

In [20]:
import os
import smtplib
from twilio.rest import Client
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email import encoders

In [21]:
source = cv2.VideoCapture(0)

while 1:
    _, image = source.read(0)
    gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    detected_faces = face_detect.detectMultiScale(gray, 1.2, 9)
    if len(detected_faces) > 1:
        continue
    for each_face in detected_faces:
        x, y, w, h = each_face
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 0, 255), 3)
        crop = gray[y:y+h, x:x+w]
        cropped_image = cv2.resize(crop, (100, 100))
        normalized_image = cropped_image/255
        reshaped_face = np.reshape(normalized_image, (1, 100, 100, 1))
        result = model.predict(reshaped_face)[0]
        if result[0] >  result[1]:
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)
            cv2.putText(image, "family member", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
            
            # Your Account SID and Auth Token from twilio.com/console
            account_sid = 'xxxxxxxxxxxxxxxxxxxxx'
            auth_token =  'xxxxxxxxxxxxxxxxxxxxx'
            
            to_phone_number = '+91xxxxxxxxxx'  # The recipient's phone number
            from_phone_number = '+xxxxxxxxxxx'  # Your Twilio phone number
            message_body = 'Family member entered your room!'
            client = Client(account_sid, auth_token)
            message = client.messages.create(body=message_body,from_=from_phone_number,to=to_phone_number)

            sub_face = image[y:y+h, x:x+w]

            #this is the location where image is saved in .jpg extension
            FaceFileName = "Location" + str(y) + ".jpg"

            time.sleep(5)
            cv2.imwrite(FaceFileName, sub_face)

            msg = MIMEMultipart()
            img_data = open(FaceFileName, 'rb').read()
            msg['Subject'] = 'There is a Family member'
            msg['From'] = 'from@gmail.com'  # email_id fron which the mail is to be sent
            msg['To'] = 'to@gmail.com'      # email_id to which the mail is to be sent
            password='app_password'         # the app_password of from@gmail.com

            message = "Family member Entered Your Room"
            msg.attach(MIMEText(message, 'plain'))
            img = MIMEImage(img_data, name=os.path.basename(FaceFileName))
            msg.attach(img)
            s = smtplib.SMTP_SSL('smtp.googlemail.com' , 465)
            s.ehlo()


            s.login(msg['From'], password)
            s.sendmail(msg['From'], msg['To'], msg.as_string())
            break


        if result[1] >  result[0]:
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 0, 255), 2)
            cv2.putText(image, "intruder", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)

            # Your Account SID and Auth Token from twilio.com/console
            account_sid = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
            auth_token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
            to_phone_number = '+91xxxxxxxxxx'  # The recipient's phone number
            from_phone_number = '+xxxxxxxxxxx'  # Your Twilio phone number
            message_body = 'Intruder entered your room!'
            client = Client(account_sid, auth_token)
            message = client.messages.create(body=message_body,from_=from_phone_number,to=to_phone_number)


            sub_face = image[y:y+h, x:x+w]

            #this is the location where image is saved in .jpg extension
            FaceFileName = "Location" + str(y) + ".jpg"

            time.sleep(5)
            cv2.imwrite(FaceFileName, sub_face)

            msg = MIMEMultipart()
            img_data = open(FaceFileName, 'rb').read()
            msg['Subject'] = 'There is a Family member'
            msg['From'] = 'from@gmail.com'  # email_id fron which the mail is to be sent
            msg['To'] = 'to@gmail.com'      # email_id to which the mail is to be sent
            password='app_password'         # the app_password of from@gmail.com

            message = "Someone Entered Your Room"
            msg.attach(MIMEText(message, 'plain'))
            img = MIMEImage(img_data, name=os.path.basename(FaceFileName))
            msg.attach(img)
            s = smtplib.SMTP_SSL('smtp.googlemail.com' , 465)
            s.ehlo()


            s.login(msg['From'], password)
            s.sendmail(msg['From'], msg['To'], msg.as_string())
            break







    cv2.imshow('Project', image)
    key = cv2.waitKey(1)
    if key == 23:
        break
cv2.destroyAllWindows()
source.release()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
